### PR TITLE
gnutls: use default system trust storage if no other CA is set

### PR DESCRIPTION
**Pull request by dangowrt**
Signed-off-by: Daniel Golle <daniel@makrotopia.org>

### CODE REVIEW

**Comment by dangowrt** [comment]
resolves #330

**Comment by ghedo** [comment]
To be honest, I don't think patch is really needed, and someone may even not want to set any default CA on purpose, and this patch would make it impossible (while other TLS backends do allow this). But it's really not up to me to decide.

As for the implementation, instead of having that big if condition, I'd use a flag set to true by default, and set to false if the trust is set by any other mean. Something like this:

```c
  int set_system_trust = 1;

  [...]

  if(data->set.ssl.CAfile) {
    [...]
    set_system_trust = 0;
  }

#ifdef HAS_CAPATH
  if(data->set.ssl.CApath) {
    [...]
    set_system_trust = 0;
  }
#endif

#ifdef HAS_SYSTEM_TRUST
  if (set_system_trust) {
    <set system trust here>
  }
#endif
```

This way you'd also avoid that #ifdef mess. Also, I think that the system trust should be enabled even if SRP is used.

**Comment by bagder** [comment]
With the fix already merged I rather abstain from accepting this as it changes the behavior slightly and I don't think it is needed now. Thoughts?

**Comment by dangowrt** [comment]
I agree that this is no longer needed if up-to-date gnuTLS is being used. From my side, I'm fine with this patch it as in places where I needed it I by now updated gnuTLS and back-ported https://github.com/bagder/curl/commit/5a1614cecdd57cab8b4ae3e9bc19dfff5ba77e80 where ever curl is still used in older versions.

**Pull request closed without merging**
