### PR TITLE
memanalyze.pl: handle free(NULL)

### PR DESCRIPTION
**Pull request by jay**
This fix is a prerequisite for issue #156

### CODE REVIEW

**Comment by jay** [comment]
hm it says test 1903 [HTTP GET using pipelining, penalized on content-length] has failed but I can't reproduce.

**Comment by dfandrich** [comment]
test 1903 is marked as flaky, so it might not be significant.

**Comment by jay** [comment]
Dan my guess is the "Handle *n* Completed" is probably out of order. It would be nice to know for certain though. I've submitted pr #159 to change the CI config to dump the output when a test fails.

**Comment by elfring** [comment]
How often does the function call "`free(NULL)`" occur?
Can it be avoided?

**Comment by jay** [comment]
For certain pointers free(NULL) already is avoided by checking if(x) free(x). Your pull request at #156 is to remove those checks. Whether or not they are necessary is besides the point here.

**Comment by elfring** [comment]
Does the updated script warn if any source code tries to free a null pointer eventually?

**Comment by jay** [comment]
No, the updated script does not warn on free(NULL).

**Comment by elfring** [comment]
Would such a warning be also useful?

**Comment by jay** [comment]
I doubt it.

**Comment by bagder** [comment]
Thanks! Merged in commit f39b1c08

**Pull request closed without merging**
