### PR TITLE
Hash unit testing

### PR DESCRIPTION
**Pull request by aavina**
Added unit1602 which exposes a bug in hash.c `Curl_hash_clean` function. Test currently fails because of a Floating point exception in the hash compare function `Curl_hash_str` due to `slots_num`being reset by `Curl_hash_clean` prior to attempting to add another key/value pair with `Curl_hash_add`.

### CODE REVIEW

**Comment by tvbuehler** [comment]
I would have hoped this results in a standard segfault / nullptr deref, not a floating point exception..

I think commits should reflect single logical changes and not your steps in developing them, so maybe you could use `git rebase --interactive` to squash the changes so far into a single commit. ([docs/CONTRIBUTE](https://github.com/bagder/curl/blob/master/docs/CONTRIBUTE) also asks for a linear history, i.e. rebase instead of merge)

**Comment by aavina** [comment]
Will do. I'll rebase and submit a pull request again.

**Comment by tvbuehler** [comment]
Just for the record: you can update a pull request by updating the branch you did the pull request with (`aavina:hash_unit_testing` in this case); use `git push -f` to have it overwrite the old history.

**Comment by aavina** [comment]
Ok, thanks for the info. I'll keep it in mind for future pull reqs.

**Pull request closed without merging**
