### PR TITLE
mbedtls: Fix pinned key return value on fail. draft1

### PR DESCRIPTION
**Pull request by sithglan**
- Switch from verifying a pinned public key in a callback to right after
the certificate verification.

### CODE REVIEW

**Comment by sithglan** [comment]
This works for me. And it fixes the problem with checking the cert after resumption and makes it possible to disable verifypeer by also using certificate pinning. I tested it since it was created in my binary and had no issues with it.

**Comment by jay** [comment]
Before this goes in it must be fixed so that the input for [`mbedtls_pk_write_pubkey_der`](https://tls.mbed.org/api/pk_8h.html#af5b7c3953ad6fe8be09d35508ee569f6) will be a non-const key instead of const. I just finished a second draft where I wrote what I thought would be the correct code to do that however I likely missed something because it does not work properly. All pinned verification fails and I've yet to debug. You can find the latest changes in the [draft branch for this issue](https://github.com/bagder/curl/compare/master...jay:fix_mbedtls_pinned_key?expand=1). I'll take another look soon.

**Comment by jay** [comment]
@sithglan This landed in d58ba66, thanks for your help. All the SSLpinning tests pass now.
`runtests.pl 2034 2035 2037 2038 2041 2042 2048`

~~~
test 2034...[simple HTTPS GET with DER public key pinning]
-pd---e--- OK (1   out of 7  , remaining: 00:30)
test 2035...[HTTPS wrong DER pinnedpubkey but right CN]
------e--- OK (2   out of 7  , remaining: 00:14)
test 2037...[simple HTTPS GET with PEM public key pinning]
-pd---e--- OK (3   out of 7  , remaining: 00:08)
test 2038...[HTTPS wrong PEM pinnedpubkey but right CN]
------e--- OK (4   out of 7  , remaining: 00:04)
test 2041...[simple HTTPS GET with base64-sha256 public key pinning]
-pd---e--- OK (5   out of 7  , remaining: 00:02)
test 2042...[HTTPS wrong base64-sha256 pinnedpubkey but right CN]
------e--- OK (6   out of 7  , remaining: 00:01)
Warning: test2048 not present in tests/data/Makefile.inc
test 2048...[pinnedpubkey no-match must fail even when insecure]
------e--- OK (7   out of 7  , remaining: 00:00)
TESTDONE: 7 tests out of 7 reported OK: 100%
TESTDONE: 7 tests were considered during 8 seconds.
~~~

~~~
curl 7.47.0-DEV (i686-w64-mingw32) libcurl/7.47.0-DEV mbedTLS/2.2.1 zlib/1.2.8 libidn/1.32 libssh2/1.6.0 nghttp2/1.6.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS Debug TrackMemory IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz HTTP2
~~~

**Comment by sithglan** [comment]
Hello Jay,

> @sithglan This landed in d58ba66, thanks for your help. All the
> SSLpinning tests pass now.

thank you for cleaning this up. I tested it and it works for me
perfectly. Thank you again.

Cheers,
        Thomas

**Pull request closed without merging**
