### PR TITLE
use openssl's built in verify path as fallback

### PR DESCRIPTION
**Pull request by lnussel**
Trying to verify a peer without having any root CA certificates
registered won't work. So use openssl's built in default as
fallback.

### CODE REVIEW

**Comment by bagder** [comment]
What built-ins is that using then? We would need documentation for that behavior!

**Comment by lnussel** [comment]
Am 26.03.2015 um 23:54 schrieb Daniel Stenberg:
> What built-ins is that using then?

The ones openssl was built with. On Linux that could be the well
known bundle file or directory in /etc or something different.
On openSUSE for example openSSL nowdays uses a private location
managed by p11-kit.

**Comment by bagder** [comment]
Thanks!

(In good old OpenSSL tradition, the SSL_CTX_set_default_verify_paths() function is completely undocumented so reading the code is the only way to really learn what it does - and yet it seems to have been around since 1999 .)

Why is it better to hand the path decisions over to OpenSSL ? Using CAs is about trust so isn't it better to be more explicit exactly which trust store you use? Also, I've built OpenSSL many times and I've never even seen the option where I tell it which cert store to use by default so I will assume many people building OpenSSL will just get a random default that is not at all "better" than the one curl tries to carefully detect and use. I also cannot find any OpenSSL documentation explaining how it sets its defaults. Can you?

Also, your updated wording of docs/SSLCERTS must not assume that curl on Linux == OpenSSL. There are no less than 8 different TLS backends frequently used with curl on Linux.

**Comment by lnussel** [comment]
Daniel Stenberg schrieb:
> Why is it better to hand the path decisions over to OpenSSL ? Using
> CAs is about trust so isn't it better to be more explicit exactly
> which trust store you use?

Well, if you are compiling curl for one specific use case then maybe
you want to use custom settings indeed. In a Linux distribution
however curl is just one piece somewhere in the middle of the stack.
openSSL is the component that actually interfaces with the
certificate store so it's desirable let openssl decide and to avoid
hardcoding custom settings into hundreds of applications higher up
the stack.

> Also, I've built OpenSSL many times and
> I've never even seen the option where I tell it which cert store to
> use by default so I will assume many people building OpenSSL will just
> get a random default that is not at all "better" than the one curl
> tries to carefully detect and use. I also cannot find any OpenSSL
> documentation explaining how it sets its defaults. Can you?

https://github.com/openssl/openssl/blob/master/INSTALL#L50
https://github.com/openssl/openssl/blob/master/crypto/cryptlib.h#L84

> Also, your updated wording of docs/SSLCERTS must not assume that curl
> on Linux == OpenSSL. There are no less than 8 different TLS backends
> frequently used with curl on Linux.

Hmm, ok. I'll try to reword. GnuTLS should also use
gnutls_certificate_set_x509_system_trust(). I don't know about the
other libs.

**Comment by bagder** [comment]
--openssldir=DIR Directory for OpenSSL files. If no prefix is specified,
                the library files and binaries are also installed there.

Right, but I don't want to point out any "openssl files", I would like to tell it where the default CAs to use are... No surprise then I've not seen the option before! It tells me that they (the OpenSSL team) don't particularly want us to do this.

**Comment by jay** [comment]
I wonder if this could open up a vulnerability. A problem in Windows is you may have software that comes with OpenSSL DLLs (in other words it's not a package on its own) and in those DLLs the paths are hard coded. A less privileged user may be able to come along and create that hard coded path if it doesn't exist and then write to it. For example I'm using a limited user account right now in Windows 7 x64 and I can create `C:\usr\local`. You can argue that it's the developer's fault for building like that, and I guess you'd be partially right. Hard coded paths just don't work well for Windows. I have a build of OpenSSL for the Automated GnuWin32 downloader and in the build files I have special instructions to override the path, here's what I say in the instructions:
```
Hard coded paths in openssl can be a security issue on windows and the 
abstraction in openssl source makes it hard to patch for this issue.
Instead I set openssldir to a phony directory that can't be opened by CreateFile().
```
The phony path I use is 
`./config no-capieng enable-camellia --openssldir="?:\*THERE_IS_NO_DEFAULT_DIRECTORY_SET_ENVIRONMENT_VARIABLES_INSTEAD*"`

It basically never happens that you have just one version of the shared library openssl. People distribute the DLLs with their software. This is still beneficial because when a new version of a DLL comes along you can just swap it out (assuming ABI).

Now aside from what you think of Windows, this is reality, right now. Anyone else have 2 cents about this? Could there be an impact on other platforms? Maybe there should be a new option like `CURLOPT_SSL_USE_HARDCODED_DIR` or something. We already have at least in the curl tool on Windows it will scan the path for curl-ca-bundle.crt, which you could make arguments for or against, but enough admins are smart enough to lock down the path and there are registry settings for hardening purposes so it's not really an issue as far as I'm concerned.

**Comment by bagder** [comment]
Thanks @jay for these additional consideration points.

I also believe that the Windows builds of curl are the primary ones that will build without default CA cert paths so they are the ones that are most likely to "hit" this new code "unintentionally". On almost all other OSes I can think of, curl builds will fine a cert store to use as default and you pretty much HAVE TO explicitly tell libcurl to not have one to make use of this new code @lnussel suggests.

The other major group being the ones that build libcurl cross-compiled or for other sorts of embedded devices with more custom layouts or bare-bones systems.

**Comment by lnussel** [comment]
IOW developers on other OSes just continue to pass the ca path explicitly to libcurl like they did before.

Anyways, if you have concerns it should be easy to add yet another configure option to enable the fallback.

**Comment by bagder** [comment]
Hm, yes with a configure option I would not have any concerns at all left.

**Comment by bagder** [comment]
It's been a month with no update. We can also re-open again if given attention.

**Pull request closed without merging**
