### PR TITLE
Clarify the CURLMOPT_TIMERFUNCTION docs, add an example.

### PR DESCRIPTION
**Pull request by stapelberg**

### CODE REVIEW

**Comment by bagder** [comment]
Thanks a lot! A little nit though: the timer should in fact not be repeating, you will get an updated timer callback for the next timout once this has fired (or not if there's then no more timeouts). Can you update the patch accordingly?

**Comment by stapelberg** [comment]
Thanks for the correction. I’ve updated the pull request, please take another look.

**Comment by JCMais** [comment]
So if the timeout is -1 I should delete the timer and not be calling curl_multi_socket_action after?

I'm asking that because I saw a bunch of code using something like that:

    if ( timeout_ms <= 0 ) {
          //call callback now
     } else {
          //create a new timer with given timeout. 
      }

And that means, they are probably wrong.

**Comment by stapelberg** [comment]
@JCMais Well, it doesn’t hurt to call it, but I think it’s unnecessary. The biggest downside is likely that it wastes power on mobile devices. @bagder, please correct me if I’m wrong :).

**Comment by bagder** [comment]
-1 means that there is no timeout, you _can_ still call libcurl but it would be rather pointless and waste CPU, just as @stapelberg says.

When it says the timout is 0, it just means that the timeout as already expired and you should call the necessary function as soon as possible. *not* repeatedly as the updated pull requests says. The timeouts told by libcurl are always single-shot - and 0 is no exception to that.

**Comment by stapelberg** [comment]
@bagder I’ve fixed the part about -1. Please take another look and consider merging this PR :).

**Comment by bagder** [comment]
gboolean ? should we really include such specific and peculiar types in a generic example section? 

Is that glib-based code or what is it?

**Comment by stapelberg** [comment]
Yes, `g_timeout_add` is a glib function, so I think it’s idiomatic and good style to use the glib types as well.

I get your point about trying to make examples not specific to a certain environment, but consider that the very purpose of the `CURLMOPT_TIMERFUNCTION` callback is to integrate curl into third-party environments. I feel like having an example with a widely-available and used library like glib is a good thing.

**Comment by bagder** [comment]
Fair enough! Thanks a lot for your work, this now landed in cc0e7ebc.

**Pull request closed without merging**
