### PR TITLE
Don't check for continuation if we're executing a CUSTOMREQUEST

### PR DESCRIPTION
**Pull request by ehlertjd**
Closes bagder/curl#486

### CODE REVIEW

**Comment by captain-caveman2k** [comment]
The fix seems simple enough.

Unfortunately I'm not near any of my Linux boxes at the moment so I was wondering do the Imap tests still run with this fix?

**Comment by bagder** [comment]
> I was wondering do the Imap tests still run with this fix?

The travis-CI tests says all OK here, so I would say yes they do! =)

**Comment by ehlertjd** [comment]
I can also verify that they passed on my test system:

uname -a

Linux build-test 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15
17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by captain-caveman2k** [comment]
@bagder Cool - as I've been away from the project for a but I couldn't remember if Travis-CI ran the test suit or not :-/

@ehlertjd Are you able to generate a custom request test as well. Again I can't remember if I wrote one when we added custom request support :-(

**Comment by ehlertjd** [comment]
I'll take a look to see what's out there and get back.

**Comment by ehlertjd** [comment]
I added a test (#841) that demonstrates the issue (in prior branches) and that the issue is fixed here. I also verified that there are a 11 other CUSTOMREQUEST tests in the IMAP suite. PR is pending Travis-CI validation.

**Pull request closed without merging**
