### PR TITLE
Ssl version validity checks

### PR DESCRIPTION
**Pull request by jay**
Changes made as discussed [here](http://curl.haxx.se/mail/lib-2015-02/0060.html) (last paragraph). The unknown value check could be expanded to include a check in url.c to check for an unknown version value in the parameter, like this:
```c
#ifdef USE_SSL
    data->set.ssl.version = va_arg(param, long);
    if((data->set.ssl.version < 0)
       || (data->set.ssl.version >= CURL_SSLVERSION_LAST))
      result = CURLE_UNKNOWN_PARAM_VALUE; //or something..
#else
    result = CURLE_UNKNOWN_OPTION;
#endif
```
Note the parameter is still set even though it's unknown. I figure it would be better to do that to cause the fail later on in the SSL since that will be visible to the user rather than just ignore the value and fail silently not sure.

### CODE REVIEW

**Comment by jay** [comment]
On second thought it may be better to handle the unknown value check in vtls. Thoughts?

**Comment by bagder** [comment]
Yeah, I think we should be able to catch invalid values in a global place instead of having basically the same check spread all over.

**Comment by jay** [comment]
Alright I've consolidated in vtls, let me know what you think.

**Comment by bagder** [comment]
Thanks! Merged as of commit e7a289ebb

**Pull request closed without merging**
