### PR TITLE
optimization // moved common variable out of #ifdef

### PR DESCRIPTION
**Pull request by snikulov**
Removed duplicated code out of ```#ifdef <some ssl engine>```

### CODE REVIEW

**Comment by snikulov** [comment]
windows build should be fixed with #617

**Comment by jay** [comment]
Maybe it was like that purposely.

**Comment by bagder** [comment]
Nah, it wasn't on purpose. I think it grew into that as originally not all the backends had that state so it was a waste to add state variables that weren't used.

**Comment by snikulov** [comment]
@jay It's not. I also think initially that it was intentional or at least position has some meaning. 
But after some investigation decide that it was copy-paste which violates DRY.

**Comment by jay** [comment]
Very well guys, just landed. Thanks Sergei

**Pull request closed without merging**
