### PR TITLE
Deletion of unnecessary checks before some function calls

### PR DESCRIPTION
**Pull request by elfring**
* [The function "free"](http://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") is documented in the way that no action shall occur for a passed null pointer. Redundant safety checks can be avoided.
* The following functions perform also input parameter validation.
  * [Curl_cookie_cleanup](https://github.com/bagder/curl/blob/df5578a7a304a23f9aa3670daff8573ec3ef416f/lib/cookie.c#L1207 "Cookie clean-up")
  * [curl_formfree](https://github.com/bagder/curl/blob/df5578a7a304a23f9aa3670daff8573ec3ef416f/lib/formdata.c#L956 "Release a form post chain.")

  It is therefore not needed that a function caller repeats a corresponding check.

### CODE REVIEW

**Comment by nickzman** [comment]
The problem is, there are some old systems out there that ignore the spec and crash on free(NULL), such as Netware, Palm OS, and some old Unix OSes. Do we care enough about supporting those old systems to merge this?

**Comment by jay** [comment]
I didn't know that. I know of some that crash on `fclose(NULL)` though. There are other places in the code that just do a `free` (maps to `Curl_cfree`) without the check. Also I'm making changes right now where I rely on `free(NULL)` to be fine so if it's not I think we should address it, have a rpl_free or something for those problem systems rather than scruff it all up with if(x) free(x) everywhere.

**Comment by bagder** [comment]
It does scare me a little to do such a massive change without it being triggered by a problem.

But even more important: this change immediately fails our test suite build/run due to the memory debug system logging nils that memanalyze.pl doesn't like:

test 0001...[HTTP GET]

** MEMORY FAILURE
Not recognized input line: free((nil))
Not recognized input line: free((nil))
Not recognized input line: free((nil))
Not recognized input line: free((nil))
Not recognized input line: free((nil))
Not recognized input line: free((nil))
Not recognized input line: free((nil))
Not recognized input line: free((nil))

**Comment by bagder** [comment]
Additionally, but rather minor checksrc complains:

../lib/formdata.c:974:7: warning: if with space
     if (!(form->flags & HTTPPOST_PTRNAME))
       ^
../lib/http.c:1826:7: warning: not indented 2 steps, uses 4)
       /* Free to avoid leaking memory on multiple requests*/
       ^
../lib/http.c:1871:5: warning: if with space
   if (Curl_checkheaders(conn, "User-Agent:")) {
     ^

**Comment by elfring** [comment]
How do you think about another configuration check like "`AC_FUNC_FREE`" as a companion to [the macro call "`AC_FUNC_MALLOC`"](http://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Particular-Functions.html "Checking memory management interface?") in your build specification?

**Comment by bagder** [comment]
I want a patch that cleans up the code to be able to run all test cases fine after being applied.

**Comment by elfring** [comment]
@bagder: Do you want another variant for my update suggestion?

**Comment by bagder** [comment]
Yes, if you want this change to go through. I don't personally feel this is important so I rather not spend a lot of time on it myself.

**Comment by elfring** [comment]
Would any other software developer like to contribute fixes for the script "memanalyze.pl"?

**Comment by jay** [comment]
@elfring I put in a pr for the memanalyze issue. You'd still need to take care of the three code style issues Daniel mentioned earlier if you want to pursue this further.

**Comment by elfring** [comment]
In which order do you prefer corresponding software updates?
 1. Integration of my update suggestion and then further fixes for coding style
 2. Correction of code style issues and then another try for the clean-up around unnecessary checks

**Comment by jay** [comment]
What is your "update suggestion", I don't see it. Refer to Daniel's earlier comment:
> I want a patch that cleans up the code to be able to run all test cases fine after being applied.

**Comment by elfring** [comment]
It seems that I overlooked a few details from [your coding style](https://github.com/bagder/curl/blob/17abfd5a4b0836d28c65ad7909538357ac817b8a/docs/CONTRIBUTE#L90 "cURL Coding Standards"). Will it be acceptable for you that I could fix corresponding implementation details by another commit on the same branch for this pull request?
(Otherwise: Do you want a separate pull request without the mentioned mistakes when the memory debug system will be improved?)

**Comment by bagder** [comment]
I do not want to (deliberately) merge any patch with wrong coding style or compiler warnings, so please fixup them!

**Comment by elfring** [comment]
I hope that [the next pull request](https://github.com/bagder/curl/pull/164 "Delete unnecessary checks before some function calls.") will be more acceptable for you.

**Pull request closed without merging**
