### PR TITLE
CMake: Problems with include directories / files

### PR DESCRIPTION
**Pull request by jzakrzewski**
Fixed problems I encountered when building cURL 7.44.0 on Windows / Linux / Solaris. Build has been done with libSSH2, OpenSSL, openLDAP, Heimdal / WINSSPI.

### CODE REVIEW

**Comment by bagder** [comment]
@snikulov, can you give this a look and tell me what you think?

**Comment by snikulov** [comment]
@jzakrzewski Could you please elaborate more on this change?
What Windows and compiler version do you using?
And what problem you've encountered?

This change does not make sense to me, because I see no changes in cmake build with it.
Perhaps it is because of different configurations we using.

I've discovered one issue - if OpenSSL/Windows SSPI both defined we got redefinition error during compilation
```lib\urldata.h(322): error C2020: 'connecting_state' : 'struct' member redefinition [C:\WORK\GITHUB\check.curl\bagder.curl\b.msvc\tests\server\sockfilt.vcxproj]```

But your change does not solve it.
Looks like it must be exclusive options.

**Comment by jzakrzewski** [comment]
OK. So this is what I'm getting without those changes:
```
D:\src\curl-7.44.0\build\win32-x86-release>cmake.exe -G "NMake Makefiles" ../..
-DCMAKE_INSTALL_PREFIX="D:/local/curl-7.44.0/win32-x86-release" -DSSL_EAY_RELEAS
E=%LIB_DIR%/ssleay32.lib -DLIB_EAY_RELEASE=%LIB_DIR%/libeay32.lib -DOPENSSL_INCL
UDE_DIR=%INC_DIR%/OpenSSL/include -DLIBSSH2_LIBRARY=%LIB_DIR%/libssh2.lib -DLIBS
SH2_INCLUDE_DIR=%INC_DIR%/LibSSH2 -DCMAKE_LDAP_LIB=%LIB_DIR%/openldap.lib -DCMAK
E_LDAP_INCLUDE_DIR=%INC_DIR%/OpenLDAP -DCMAKE_USE_OPENLDAP=ON -DZLIB_LIBRARY=%LI
B_DIR%/zlibwapi.lib -DZLIB_INCLUDE_DIR=%INC_DIR%/zlib/include  -DBUILD_CURL_TEST
S=OFF -DUSE_WIN32_LDAP=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_WINDOWS_SSPI=
ON
-- The C compiler identification is MSVC 18.0.21005.1
-- Check for CL compiler version
-- Check for CL compiler version - 1800
-- Check if this is a free VC compiler
-- Check if this is a free VC compiler - no
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio
12.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio
12.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Warning at CMakeLists.txt:48 (message):
  the curl cmake build system is poorly maintained.  Be aware


-- curl version=[7.44.0]
-- Performing Test HAVE_SOCKADDR_IN6_SIN6_ADDR
-- Performing Test HAVE_SOCKADDR_IN6_SIN6_ADDR - Failed
-- Performing Test HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID
-- Performing Test HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID - Failed
CMake Warning at CMakeLists.txt:196 (message):
  struct sockaddr_in6 not available, disabling IPv6 support


CMake Warning at CMakeLists.txt:230 (message):
  Found no *nroff program


-- Looking for getch in ws2_32;
-- Looking for getch in ws2_32; - found
-- Looking for getch in winmm;ws2_32
-- Looking for getch in winmm;ws2_32 - found
openssl_version_str# define OPENSSL_VERSION_NUMBER  0x1000204fL
-- Found OpenSSL: optimized;D:/runtime_libs/bin/win32-x86-release/ssleay32.lib;d
ebug;D:/runtime_libs/bin/win32-x86-release/ssleay32.lib;optimized;D:/runtime_lib
s/bin/win32-x86-release/libeay32.lib;debug;D:/runtime_libs/bin/win32-x86-release
/libeay32.lib (found version "1.0.2d")
-- Looking for openssl/crypto.h
-- Looking for openssl/crypto.h - found
-- Looking for openssl/engine.h
-- Looking for openssl/engine.h - found
-- Looking for openssl/err.h
-- Looking for openssl/err.h - found
-- Looking for openssl/pem.h
-- Looking for openssl/pem.h - found
-- Looking for openssl/pkcs12.h
-- Looking for openssl/pkcs12.h - found
-- Looking for openssl/rsa.h
-- Looking for openssl/rsa.h - found
-- Looking for openssl/ssl.h
-- Looking for openssl/ssl.h - not found
-- Looking for openssl/x509.h
-- Looking for openssl/x509.h - found
-- Looking for openssl/rand.h
-- Looking for openssl/rand.h - found
-- Looking for ldap_init in D:/runtime_libs/bin/win32-x86-release/openldap.lib;w
inmm;ws2_32;optimized;D:/runtime_libs/bin/win32-x86-release/ssleay32.lib;debug;D
:/runtime_libs/bin/win32-x86-release/ssleay32.lib;optimized;D:/runtime_libs/bin/
win32-x86-release/libeay32.lib;debug;D:/runtime_libs/bin/win32-x86-release/libea
y32.lib
-- Looking for ldap_init in D:/runtime_libs/bin/win32-x86-release/openldap.lib;w
inmm;ws2_32;optimized;D:/runtime_libs/bin/win32-x86-release/ssleay32.lib;debug;D
:/runtime_libs/bin/win32-x86-release/ssleay32.lib;optimized;D:/runtime_libs/bin/
win32-x86-release/libeay32.lib;debug;D:/runtime_libs/bin/win32-x86-release/libea
y32.lib - found
-- Looking for ber_init in lber;D:/runtime_libs/bin/win32-x86-release/openldap.l
ib;winmm;ws2_32;optimized;D:/runtime_libs/bin/win32-x86-release/ssleay32.lib;deb
ug;D:/runtime_libs/bin/win32-x86-release/ssleay32.lib;optimized;D:/runtime_libs/
bin/win32-x86-release/libeay32.lib;debug;D:/runtime_libs/bin/win32-x86-release/l
ibeay32.lib
-- Looking for ber_init in lber;D:/runtime_libs/bin/win32-x86-release/openldap.l
ib;winmm;ws2_32;optimized;D:/runtime_libs/bin/win32-x86-release/ssleay32.lib;deb
ug;D:/runtime_libs/bin/win32-x86-release/ssleay32.lib;optimized;D:/runtime_libs/
bin/win32-x86-release/libeay32.lib;debug;D:/runtime_libs/bin/win32-x86-release/l
ibeay32.lib - not found
-- Looking for include files HAVE_LDAP_H
-- Looking for include files HAVE_LDAP_H - found
-- Looking for include files HAVE_LBER_H
-- Looking for include files HAVE_LBER_H - found
-- Performing Test NOT_NEED_LBER_H
-- Performing Test NOT_NEED_LBER_H - Success
-- Looking for include files HAVE_LDAP_SSL_H
-- Looking for include files HAVE_LDAP_SSL_H - not found.
-- Looking for include files HAVE_LDAPSSL_H
-- Looking for include files HAVE_LDAPSSL_H - not found.
-- Looking for idna_to_ascii_lz in idn;D:/runtime_libs/bin/win32-x86-release/ope
nldap.lib;winmm;ws2_32;optimized;D:/runtime_libs/bin/win32-x86-release/ssleay32.
lib;debug;D:/runtime_libs/bin/win32-x86-release/ssleay32.lib;optimized;D:/runtim
e_libs/bin/win32-x86-release/libeay32.lib;debug;D:/runtime_libs/bin/win32-x86-re
lease/libeay32.lib
-- Looking for idna_to_ascii_lz in idn;D:/runtime_libs/bin/win32-x86-release/ope
nldap.lib;winmm;ws2_32;optimized;D:/runtime_libs/bin/win32-x86-release/ssleay32.
lib;debug;D:/runtime_libs/bin/win32-x86-release/ssleay32.lib;optimized;D:/runtim
e_libs/bin/win32-x86-release/libeay32.lib;debug;D:/runtime_libs/bin/win32-x86-re
lease/libeay32.lib - not found
-- Looking for libssh2_version
-- Looking for libssh2_version - found
-- Looking for libssh2_init
-- Looking for libssh2_init - found
-- Looking for libssh2_exit
-- Looking for libssh2_exit - found
-- Looking for libssh2_scp_send64
-- Looking for libssh2_scp_send64 - found
-- Looking for libssh2_session_handshake
-- Looking for libssh2_session_handshake - found
-- Performing Test USE_UNIX_SOCKETS
-- Performing Test USE_UNIX_SOCKETS - Failed
-- Looking for include files HAVE_WINDOWS_H
-- Looking for include files HAVE_WINDOWS_H - not found.
-- Looking for include files HAVE_WINSOCK_H
-- Looking for include files HAVE_WINSOCK_H - not found.
-- Looking for include files HAVE_WS2TCPIP_H
-- Looking for include files HAVE_WS2TCPIP_H - not found.
-- Looking for include files HAVE_WINSOCK2_H
-- Looking for include files HAVE_WINSOCK2_H - not found.
-- Looking for include files HAVE_STDIO_H
-- Looking for include files HAVE_STDIO_H - not found.
-- Looking for include files HAVE_SYS_FILIO_H
-- Looking for include files HAVE_SYS_FILIO_H - not found.
-- Looking for include files HAVE_SYS_IOCTL_H
-- Looking for include files HAVE_SYS_IOCTL_H - not found.
-- Looking for include files HAVE_SYS_RESOURCE_H
-- Looking for include files HAVE_SYS_RESOURCE_H - not found.
-- Looking for include files HAVE_SYS_UIO_H
-- Looking for include files HAVE_SYS_UIO_H - not found.
-- Looking for include files HAVE_SYS_UN_H
-- Looking for include files HAVE_SYS_UN_H - not found.
-- Looking for include files HAVE_ARPA_TFTP_H
-- Looking for include files HAVE_ARPA_TFTP_H - not found.
-- Looking for include files HAVE_ASSERT_H
-- Looking for include files HAVE_ASSERT_H - not found.
-- Looking for include files HAVE_CRYPTO_H
-- Looking for include files HAVE_CRYPTO_H - not found.
-- Looking for include files HAVE_DES_H
-- Looking for include files HAVE_DES_H - not found.
-- Looking for include files HAVE_ERR_H
-- Looking for include files HAVE_ERR_H - not found.
-- Looking for include files HAVE_ERRNO_H
-- Looking for include files HAVE_ERRNO_H - not found.
-- Looking for include files HAVE_IDN_FREE_H
-- Looking for include files HAVE_IDN_FREE_H - not found.
-- Looking for include files HAVE_IFADDRS_H
-- Looking for include files HAVE_IFADDRS_H - not found.
-- Looking for include files HAVE_KRB_H
-- Looking for include files HAVE_KRB_H - not found.
-- Looking for include files HAVE_LIBGEN_H
-- Looking for include files HAVE_LIBGEN_H - not found.
-- Looking for include files HAVE_LIMITS_H
-- Looking for include files HAVE_LIMITS_H - not found.
-- Looking for include files HAVE_LOCALE_H
-- Looking for include files HAVE_LOCALE_H - not found.
-- Looking for include files HAVE_NETINET_TCP_H
-- Looking for include files HAVE_NETINET_TCP_H - not found.
-- Looking for include files HAVE_PEM_H
-- Looking for include files HAVE_PEM_H - not found.
-- Looking for include files HAVE_POLL_H
-- Looking for include files HAVE_POLL_H - not found.
-- Looking for include files HAVE_RSA_H
-- Looking for include files HAVE_RSA_H - not found.
-- Looking for include files HAVE_SSL_H
-- Looking for include files HAVE_SSL_H - not found.
-- Looking for include files HAVE_STDBOOL_H
-- Looking for include files HAVE_STDBOOL_H - not found.
-- Looking for include files HAVE_STROPTS_H
-- Looking for include files HAVE_STROPTS_H - not found.
-- Looking for include files HAVE_TLD_H
-- Looking for include files HAVE_TLD_H - not found.
-- Looking for include files HAVE_STDDEF_H
-- Looking for include files HAVE_STDDEF_H - not found.
-- Looking for include files HAVE_SYS_UTSNAME_H
-- Looking for include files HAVE_SYS_UTSNAME_H - not found.
-- Looking for include files HAVE_IDNA_H
-- Looking for include files HAVE_IDNA_H - not found.
-- Check size of size_t
-- Check size of size_t - failed
-- Check size of ssize_t
-- Check size of ssize_t - failed
-- Check size of long long
-- Check size of long long - done
-- Check size of long
-- Check size of long - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of __int64
-- Check size of __int64 - done
-- Check size of time_t
-- Check size of time_t - done
-- Looking for basename
-- Looking for basename - not found.
-- Looking for strncmpi
-- Looking for strncmpi - not found.
-- Looking for alarm
-- Looking for alarm - not found.
-- Looking for CRYPTO_cleanup_all_ex_data
-- Looking for CRYPTO_cleanup_all_ex_data - not found.
-- Looking for gethostbyname
-- Looking for gethostbyname - not found.
-- Looking for strtoll
-- Looking for strtoll - not found.
-- Looking for _strtoi64
-- Looking for _strtoi64 - not found.
-- Looking for strerror_r
-- Looking for strerror_r - not found.
-- Looking for siginterrupt
-- Looking for siginterrupt - not found.
-- Looking for fork
-- Looking for fork - not found.
-- Looking for freeaddrinfo
-- Looking for freeaddrinfo - not found.
-- Looking for freeifaddrs
-- Looking for freeifaddrs - not found.
-- Looking for pipe
-- Looking for pipe - not found.
-- Looking for ftruncate
-- Looking for ftruncate - not found.
-- Looking for getprotobyname
-- Looking for getprotobyname - not found.
-- Looking for getrlimit
-- Looking for getrlimit - not found.
-- Looking for idn_free
-- Looking for idn_free - not found.
-- Looking for idna_strerror
-- Looking for idna_strerror - not found.
-- Looking for tld_strerror
-- Looking for tld_strerror - not found.
-- Looking for setlocale
-- Looking for setlocale - not found.
-- Looking for setrlimit
-- Looking for setrlimit - not found.
-- Looking for fcntl
-- Looking for fcntl - not found.
-- Looking for ioctl
-- Looking for ioctl - not found.
-- Looking for setsockopt
-- Looking for setsockopt - not found.
-- Looking for inet_pton
-- Looking for inet_pton - not found
-- Performing Curl Test HAVE_FCNTL_O_NONBLOCK
-- Performing Curl Test HAVE_FCNTL_O_NONBLOCK - Failed
-- Performing Curl Test HAVE_IOCTLSOCKET
-- Performing Curl Test HAVE_IOCTLSOCKET - Failed
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL - Failed
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL_FIONBIO
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL_FIONBIO - Failed
-- Performing Curl Test HAVE_IOCTLSOCKET_FIONBIO
-- Performing Curl Test HAVE_IOCTLSOCKET_FIONBIO - Failed
-- Performing Curl Test HAVE_IOCTL_FIONBIO
-- Performing Curl Test HAVE_IOCTL_FIONBIO - Failed
-- Performing Curl Test HAVE_IOCTL_SIOCGIFADDR
-- Performing Curl Test HAVE_IOCTL_SIOCGIFADDR - Failed
-- Performing Curl Test HAVE_SETSOCKOPT_SO_NONBLOCK
-- Performing Curl Test HAVE_SETSOCKOPT_SO_NONBLOCK - Failed
-- Performing Curl Test HAVE_SOCKLEN_T
-- Performing Curl Test HAVE_SOCKLEN_T - Success
-- Performing Curl Test HAVE_BOOL_T
-- Performing Curl Test HAVE_BOOL_T - Failed
-- Performing Curl Test HAVE_FILE_OFFSET_BITS
-- Performing Curl Test HAVE_FILE_OFFSET_BITS - Failed
-- Performing Curl Test HAVE_GLIBC_STRERROR_R
-- Performing Curl Test HAVE_GLIBC_STRERROR_R - Failed
-- Performing Curl Test HAVE_POSIX_STRERROR_R
-- Performing Curl Test HAVE_POSIX_STRERROR_R - Failed
-- Check size of curl_off_t
-- Check size of curl_off_t - failed
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Performing Test curl_cv_recv
-- Performing Test curl_cv_recv - Failed
CMake Error at CMake/OtherTests.cmake:86 (message):
  Unable to link function recv
Call Stack (most recent call first):
  CMakeLists.txt:989 (include)


-- Configuring incomplete, errors occurred!

D:\src\curl-7.44.0\build\win32-x86-release>
```

The interesting part is here:
```
-- Looking for include files HAVE_WINDOWS_H
-- Looking for include files HAVE_WINDOWS_H - not found.
-- Looking for include files HAVE_WINSOCK_H
-- Looking for include files HAVE_WINSOCK_H - not found.
-- Looking for include files HAVE_WS2TCPIP_H
-- Looking for include files HAVE_WS2TCPIP_H - not found.
-- Looking for include files HAVE_WINSOCK2_H
-- Looking for include files HAVE_WINSOCK2_H - not found.
```
This is of course bull*. The problem is obvious when checking the error log:
```
Determining if files ldap.h;lber.h;D:/runtime_libs/external/win32-x86/LibSSH2/libssh2.h;windows.h exist failed with the following output:
Change Dir: D:/src/curl-7.44.0/build/win32-x86-release/CMakeFiles/CMakeTmp

Run Build Command:nmake /NOLOGO  "cmTryCompileExec\fast"
	"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe" -f CMakeFiles\cmTryCompileExec.dir\build.make /nologo -L                  CMakeFiles\cmTryCompileExec.dir\build

	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -E cmake_progress_report D:\src\curl-7.44.0\build\win32-x86-release\CMakeFiles\CMakeTmp\CMakeFiles 1

Building C object CMakeFiles/cmTryCompileExec.dir/CheckIncludeFiles.c.obj

	C:\PROGRA~2\MICROS~3.0\VC\bin\cl.exe  @C:\Users\DEVELO~1\AppData\Local\Temp\nmB527.tmp

CheckIncludeFiles.c

D:\src\curl-7.44.0\build\win32-x86-release\CMakeFiles\CMakeTmp\CheckIncludeFiles.c(2) : fatal error C1083: Cannot open include file: 'ldap.h': No such file or directory

NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~3.0\VC\bin\cl.exe' : return code '0x2'

Stop.

NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'

Stop.


Source:
/* */
#include <ldap.h>
#include <lber.h>
#include <D:/runtime_libs/external/win32-x86/LibSSH2/libssh2.h>
#include <windows.h>


int main(){return 0;}
```
The LDAP headers cannot be found unless I tell CMake where to look. In general we shouldn't need it but I one tried to eliminate the "always check for all headers" behaviour it has been rolled back because of some nasty dependencies on some platforms.

The second change is purely a matter of correctness. There will be warnings about redefinitions otherwise as the "windows.h" includes "winsock.h". Other good idea might be to avoid looking for (and using) "winsock.h" if "winsock2.h" is found.

**Comment by snikulov** [comment]
@jzakrzewski Well, could you please just run ```cmake.exe -G "NMake Makefiles" ../..``` and see how it goes on clean generation? 

I'm just curious which options/libraries breaks windows.h detection.
Because in my case it will be found flawlessly even on ```curl-7_44_0``` tag.

Anyway, current configuration in cmake are terrible :)

**Comment by jzakrzewski** [comment]
This seems to work without problems. The error I had (see previous comment) mentions openLDAP headers are missing. This is how I knew the discovered paths were not used. I've looked again and found that libSSH2 tests reset the CMAKE_REQUIRED_INCLUDES. Indeed, running CMake with OpenLDAP and libSSH2-related options only reproduces the error.

CMAKE_REQUIRED_INCLUDES is meant for local usage (correct me if I'm wrong) so I'd rather not enforce maintaining it's content across the entire CMake script.

What may be important (in case it's not clear): all the libraries I use are self-compiled and in non-standard paths, so neither libs nor headers are visible to compiler when I don't tell him where to look for them.

PS: Yeah, it's terrible. When I've started with it I tried to make it nicer but already initial steps have caused others some problems. Unfortunately it mimics autotools behaviour in every possible way.

**Comment by snikulov** [comment]
@jzakrzewski I suspect we should replace 

```set(CMAKE_REQUIRED_INCLUDES ${... Whatever ... _INCLUDE_DIR})```
which reset previous value to 
```list(APPEND CMAKE_REQUIRED_INCLUDES ${... Whatever ... _INCLUDE_DIR})```
or
```set(CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES} ${... Whatever ... _INCLUDE_DIR})```

@bradking What do you think?

**Comment by bradking** [comment]
@snikulov accumulating include directories for the checks makes sense since the checks are accumulating a list of headers to include.

**Comment by jzakrzewski** [comment]
I'd prefer not to accumulate in CMAKE_REQUIRED_INCLUDES but from the other hand right now the entire CMake script work this way.

If we all agree, I'll update the pull request.

**Comment by snikulov** [comment]
:+1:

**Comment by bagder** [comment]
Sorry for being a bit slow here, but is this version now using the agreed upon solution?

**Comment by jzakrzewski** [comment]
Hey, no problem. I know you're busy.

I think this is it but I wouldn't mind if someone just scanned it for stupidity ;)

**Comment by snikulov** [comment]
@jzakrzewski it's not that I'm disagree with changes, but if you work with LDAP extensively, maybe better put FindLDAP/FindOpenLDAP module to Cmake folder? 
It'll simplify CMakeLists.txt a bit.
For example from here: https://github.com/facebook/hhvm/blob/master/CMake/FindLdap.cmake

I think, _BAK variable really not good idea.

@bradking What do you think?

**Comment by jzakrzewski** [comment]
It may work but I'll have to make sure that the detection is aligned to curl's needs. When I first started to play with this I was cautious to mimic what's being done in the autotools. The two build systems must behave the same.

As for the _BAK - I couldn't figure this one out and didn't want to pollute include directories with something that does not exist.

**Comment by bradking** [comment]
@snikulov, splitting LDAP search out into dedicated find modules may be of value but is perhaps out of scope for the change here and could be done with follow-up work.  It could be part of an effort to reduce accumulation of headers/include-dirs in favor of independent checks (as @jzakrzewski points out would be better in the long run).

**Comment by snikulov** [comment]
@bradking I think nobody will start long run for better, until we have "crutch" ( Russian folklore ).
If this patch is good for you - I'll not argue to merge it.

**Comment by bagder** [comment]
Thanks everyone for weighing in. I'll merge this asap, and if someone wants to work further on improving the cmake files we can take that separately.

**Pull request closed without merging**
