### PR TITLE
CURLOPT_CABUNDLE and CURLOPT_CABUNDLESIZE with PolarSSL support

### PR DESCRIPTION
**Pull request by c0ff**
An option to set in-memory SSL CA bundle.
Implementation for the PolarSSL backend.

### CODE REVIEW

**Comment by bagder** [comment]
Thanks!

A TLS oriented feature that doesn't work with at least OpenSSL (which >90% of our users use) seems like a stretch and I think it has to work for that at least to get accepted. Also there's no documentation and as you can see, this fails the test suite (probably because of lack of symbols in docs/libcurl/symbols-in-versions)

You also need to rebase it on the current master since it doesn't merge nicely anymore.

**Comment by bagder** [comment]
I think we also need to consider a more descriptive name.

**Comment by c0ff** [comment]
Hi,

Yeah the patch feels a bit rushed. Sorry for that.
Just found how to do this in OpenSSL backend. So I will rework the patch with the support for OpenSSL, PolarSSL and mbedTLS. Would also want to add SChannel support, but I've just failed to add ALPN there, so have not much hope for this one.

A more descriptive name, you mean for the CURLOPT? May be CURLOPT_CABUNDLE_POINTER (not _DATA because there's no copying)  / CURLOPT_CABUNDLE_SIZE?

**Comment by bagder** [comment]
Yes I meant the option name. The existing ones are already confusingly named! How about CURLOPT_CA_MEM_PTR ?

**Pull request closed without merging**
