### PR TITLE
darwinssl: add support for ALPN negotiation using a private API

### PR DESCRIPTION
**Pull request by rcombs**
Pity this isn't publicly documented or exposed, but here it is.

NPN is also supported using a very similar API. I could add it if people want it, but it seems to have been entirely superseded by ALPN and I'm not sure if there's any significant support for it where its successor is unavailable.

### CODE REVIEW

**Comment by nickzman** [comment]
We absolutely cannot allow use of private API in libcurl, or else we will get our users' apps blocked from the App Store. We will have to wait for Apple to open up the NPN/ALPN APIs before we can support this.

**Comment by rcombs** [comment]
`SSLSetALPNProtocols` is added as a public API in macOS 10.13/iOS 11; once I'm on the betas I'll update this to use that.

**Comment by nickzman** [comment]
They were public API for a very short while back in the 10.10 betas, but then they removed them about three releases into the beta for some reason. Let's not merge it until we're sure they were not added by mistake.

**Comment by ePirat** [comment]
While `SSLSetALPNProtocols` is in the headers of the release version of 10.13, the Security Framework is missing the function, so compiling will work, but it will not link successfully due to the missing symbol.

Reported it to Apple as rdar://34790589

**Pull request closed without merging**
