### PR TITLE
added Windows SSL support for CMake build

### PR DESCRIPTION
**Pull request by snikulov**
Re-enabled Windows SSL support for CMake build.

Tested with MSVC 2013/2015, MinGW 5.1.0.

> c:\WORK\GitHub\curl\mingw\src>curl --version
> curl 7.45.0-DEV (Windows) libcurl/7.45.0-DEV WinSSL
> Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
> Features: SSPI Kerberos SPNEGO NTLM SSL

### CODE REVIEW

**Comment by snikulov** [comment]
@bradking Could you please review and comment? Thank you.

**Comment by bradking** [comment]
Good start.  If `HAVE_SCHANNEL_H` succeeds but `HAVE_SSPI_H` fails then one will get compilation errors with the current logic.  We cannot allow the configured header to define `USE_SCHANNEL` but not `USE_WINDOWS_SSPI`.  Please update the logic accordingly.

Style nit: the `CMakeLists.txt` file currently uses 2-space indentation but the patch adds a block using 4-space indentation.

**Comment by snikulov** [comment]
@bradking fixed both comments 5d1581c4b89b8b334de9dad5883e91ef57d88441

**Comment by bradking** [comment]
LGTM.  Please squash down to one commit.

**Comment by snikulov** [comment]
@bradking Done.
@bagder Could you please review and merge?
Thank you.

**Pull request closed without merging**
