### PR TITLE
version: Add flag CURL_VERSION_PSL for libpsl

### PR DESCRIPTION
**Pull request by jay**
As proposed by Gisle Vanem in 
https://github.com/bagder/curl/commit/e77b5b7453c1e8ccd7ec0816890d98e2f392e465#commitcomment-14739692
If there are no objections I'll land it in a few days

### CODE REVIEW

**Comment by jay** [comment]
CURL_VERSION_LIBPSL => CURL_VERSION_PSL

**Comment by gvanem** [comment]
Looks okay. I fail to see why Travis failed though.

**Comment by jay** [comment]
> I fail to see why Travis failed though.

It's because I forgot to update the known symbols list. I've now amended the commit to fix that. For future reference if you scroll down to the bottom of the ci output you can see which tests failed
TESTFAIL: These test cases failed: 1119

**Comment by bagder** [comment]
:+1: for me!

**Comment by jay** [comment]
Thanks, landed in b1f9424.

**Comment by gvanem** [comment]
Good. Can we do similar for lwIP? I.e. `CURL_VERSION_LWIP`.

**Pull request closed without merging**
