### PR TITLE
Support HTTPS proxy (--proxy https://). Support SOCKS+HTTP* proxy combo.

### PR DESCRIPTION
**Pull request by rousskov**
This feature was developed in 2013. Despite the death of one of the primary developers, we kept the code in sync with the official Curl releases, but failed to find the cycles for the official submission until now. The first sections below describe the two major parts of the new code (in a format suitable for a commit message) followed by usage examples and a to-do list.

### 1. HTTPS proxies:

```
An HTTPS proxy receives all transactions over an SSL/TLS connection.
Once a secure connection with the proxy is established, the user agent
uses the proxy as usual, including sending CONNECT requests to instruct
the proxy to establish a [usually secure] TCP tunnel with an origin
server. HTTPS proxies protect nearly all aspects of user-proxy
communications as opposed to HTTP proxies that receive all requests
(including CONNECT requests) in vulnerable clear text.

With HTTPS proxies, it is possible to have two concurrent _nested_
SSL/TLS sessions: the "outer" one between the user agent and the proxy
and the "inner" one between the user agent and the origin server
(through the proxy). This change adds supports for such nested sessions
as well.

A secure connection with a proxy requires its own set of the usual SSL
options (their actual descriptions differ and need polishing, see TODO):

  --proxy-cacert FILE        CA certificate to verify peer against
  --proxy-capath DIR         CA directory to verify peer against
  --proxy-cert CERT[:PASSWD] Client certificate file and password
  --proxy-cert-type TYPE     Certificate file type (DER/PEM/ENG)
  --proxy-ciphers LIST       SSL ciphers to use
  --proxy-crlfile FILE       Get a CRL list in PEM format from the file
  --proxy-insecure           Allow connections to proxies with bad certs
  --proxy-key KEY            Private key file name
  --proxy-key-type TYPE      Private key file type (DER/PEM/ENG)
  --proxy-pass PASS          Pass phrase for the private key
  --proxy-ssl-allow-beast    Allow security flaw to improve interop
  --proxy-sslv2              Use SSLv2
  --proxy-sslv3              Use SSLv3
  --proxy-tlsv1              Use TLSv1
  --proxy-tlsuser USER       TLS username
  --proxy-tlspassword STRING TLS password
  --proxy-tlsauthtype STRING TLS authentication type (default SRP)

All --proxy-foo options are independent from their --foo counterparts,
except --proxy-crlfile which defaults to --crlfile and --proxy-capath
which defaults to --capath.

Curl now also supports %{proxy_ssl_verify_result} --write-out variable,
similar to the existing %{ssl_verify_result} variable.
```

### 2. SOCKS proxy + HTTP/HTTPS proxy combination:

```
If both --socks* and --proxy options are given, Curl first connects to
the SOCKS proxy and then connects (through SOCKS) to the HTTP or HTTPS
proxy.
```

### 3. Copyright statement:

Copyright (C) 2015 The Measurement Factory, Inc.
Distributed under the terms of the Curl project itself.
Authors: Dmitry Kurochkin, Vasy Okhin, and Alex Rousskov.

### 4. Usage examples:

```
proxy='--proxy https://localhost:3129/'
ca='--proxy-cacert ssl_cert/myCA.pem'
curl $ca $proxy http://www.example.com
curl $ca $proxy https://www.example.com
curl $ca $proxy --proxytunnel https://www.example.com

socks='--socks5 127.0.0.1:1080'
curl $ca $proxy --proxytunnel $socks http://www.example.com
curl $ca $proxy --proxytunnel $socks https://www.example.com

curl --insecure --proxytunnel $ca $socks $proxy \
	ftps://user:pass@127.0.0.1/example.txt

curl --insecure --proxytunnel $ca $socks $proxy \
    --ftp-ssl ftp://user:pass@127.0.0.1/example.txt

format='OR=%{ssl_verify_result},PR=%{proxy_ssl_verify_result}\n\n';
curl --proxy-insecure -w $format $proxy https://www.example.com
```

### 5. TODO:

1. Sync with the latest master. The last sync was at curl-7_42_0 tag. The current changes work for Curl v7.42.1 as well.
2. Change --proxy-foo option descriptions. The current approach of appending "for proxy" to the original --foo description does not work well in most cases.
3. Add --proxy-foo options to mimic --tlsv1.0, --tlsv1.1, and --tlsv1.2 added to Curl v7.42, after the active work on this feature has stopped.
4. Finalize version-related TBD symbols.
5. Man page updates.

The code passes "make check" tests and has seen more than a year of light use in a few different environments.

We will do our best to address your change requests, but we do _not_ consider ourselves Curl experts, and are looking forward to finally leaving this code in more capable hands :-). Thank you for Curl!

### CODE REVIEW

**Comment by bagder** [comment]
Wow, this is quite a mouthful but also a feature I've had on my own roadmap for some time. It's great to see it here. Thanks a lot for your work on this! Please give me some time and I will give it a proper review and get back with comments within a week.

**Comment by rousskov** [comment]
"Mouthful" does not really describe it IMO. Secure HTTP tunnels inside secure tunnels is more like choking on a fish that chokes on another fish stuffed with anchovies :-).

Your automated CI tests show our HTTPS proxy changes fail test case #1903 with clang. We believe this is due to a race condition in the test case itself. If we adjust the tests/http_pipe.py code in v7.42.1  to delay the 100K response by one second, we get reliable test case #1903 (and #1901) failures with or without HTTPS proxy changes.

```
       elif path == '/100k.txt':
         body = '0123456789abcdef' * 6400
+        time.sleep(1)
         result += self._BuildResponse(
```


Sorry, we could not find a way to quickly fix the test case. I hope you are not going to hold that against us.

**Comment by bagder** [comment]
Regarding point (2), that you allow _both_ a socks proxy and a HTTPS proxy, what is the reasoning for that? It is change to how libcurl works since before. To me it sounds like a highly specific and rare setup.

I did a quick test now to rebase this patch set to the latest git master, and there are some places that need some manual editing to go through.

**Comment by rousskov** [comment]
We have a customer that needs to go through the SOCKS proxy to get to an HTTP[S] proxy, so we have to support that combination. I am sure this is not a common requirement, but SOCKS and HTTPS proxies are relatively uncommon on their own. From user point of view, the configuration remains straightforward and natural: If you want a proxy, use --proxy; if you want SOCKS, use --socks; and if you want both, use both options. IMHO, *not* supporting that combination is less natural than supporting it; it is a restriction that you have to document and explain.

Please let me know whether you want us to provide a master-based branch. We can certainly port our changes to current git master if you prefer not to do that yourself.

**Comment by bagder** [comment]
Ok, good enough! If you help us rebase this against master and make an updated pull-request with that, I'm prepared to get working on merging this after the 7.43.0 release.

**Comment by rousskov** [comment]
Thank you. We will rebase to master. Do you anticipate major master changes in the immediate future?
* If yes, we may want to wait for those changes to be committed before porting our code to master (so that you do not have to deal with a growing number of conflicts while the rebased code waits in the pull request queue for the 7.43.0 release).
* If not, then we will start working on this right away.

**Comment by bagder** [comment]
No, I do not anticipate (and frankly we won't allow) any major changes right now until the 7.43.0 release planned for June 17th. I'm not aware of any major changes pending for after that either. I have some http2 work in line but I find it unlikely that it would collide in any particular way with your work.

**Comment by rousskov** [comment]
This pull request #268 was against Curl branch 7_42. We have now ported our changes to master and created the corresponding pull request #305. I am closing this pull request as obsolete.

**Pull request closed without merging**
