### PR TITLE
Added AppVeyor-CI for curl 

### PR DESCRIPTION
**Pull request by snikulov**
Hello,

I've added appveyor.yml to integrate curl with AppVeyor-CI https://ci.appveyor.com
@bagder Daniel, you can add curl project to this CI server to check Windows builds.

[Build status](https://ci.appveyor.com/project/snikulov/curl)

Regards.

### CODE REVIEW

**Comment by bagder** [comment]
Thanks, I just want us to fix the existing CI problems first before we merge new ones.

**Comment by snikulov** [comment]
@bagder Unfortunately, I'm unable to help you with Apple. I have no Mac.
Only Linux/Windows.

**Comment by bagder** [comment]
Thanks! Lets see how this performs now...

**Comment by snikulov** [comment]
@bagder Could you please also enable your project in https://ci.appveyor.com ?
Thank you.

**Comment by bagder** [comment]
Ah right. Done it now...

**Pull request closed without merging**
