### PR TITLE
http: add --locations-trusted, CURLOPT_TRUSTED_AUTH

### PR DESCRIPTION
**Pull request by gnawhleinad**
Send HTTP user and password authentication to a list of trusted host
names on redirect.

Bug: https://github.com/bagder/curl/issues/475
Reported-by: @cneberg

### CODE REVIEW

**Comment by cneberg** [comment]
Thank you for looking at this. I notice the new solution you are working on only specifies the host name, and not the URL which was what was in the enhancement request. I still think specifying the whole URL including path is preferable because it fits a lot more security use cases which is extremely important especially for libcurl which is embedded in lots of applications with unpredictable use cases.  The biggest issue though is that it lost its ability to request HTTPS only for the host.

**Comment by jay** [comment]
> The biggest issue though is that it lost its ability to request HTTPS only for the host.

If you need HTTPS only couldn't you use [CURLOPT_PROTOCOLS](http://curl.haxx.se/libcurl/c/CURLOPT_PROTOCOLS.html)?

**Comment by cneberg** [comment]
Sometimes auth is over SSL, but not the download itself, multiple redirects in an SSO system may involve both.

**Comment by cneberg** [comment]
I'm advocating the option which protects the auth credentials be as simple and flexible as possible.

**Comment by bagder** [comment]
simple and flexible, sure, but it also needs to be able to restrict the auth to exactly only the hosts the user wants to allow. Therefore I suggest we support limiting auth to specific scheme + host + port + path combos, where we can possibly allow wildcards for some of the fields.

**Comment by gnawhleinad** [comment]
> specific scheme + host + port + path combos, where we can possibly allow wildcards for some of the fields

Are you proposing `--locations-trusted <list of [protocol://]host[:port][path]>`? Is this strict matching? Or, should we allow any subdomain? Any path that starts with?

**Comment by cneberg** [comment]
That looks good to me, each of the components are optional and  I'd suggest strict matching on the domain (no subdomains), and any path that starts with the path specified, otherwise you'll have to deal with optional trailing slashes which always cause confusion on URL matches.

**Pull request closed without merging**
