### PR TITLE
Try harder ro make CURLINFO_ACTIVESOCKET work.

### PR DESCRIPTION
**Pull request by Andersbakken**

### CODE REVIEW

**Comment by bagder** [comment]
Thanks! I'm curious on which situation(s) this is necessary? It seems like we have a lot of checks in Curl_getconnectinfo() to figure out if its a good socket to return and this suggested change basically offers a big fat way around those checks. If (one or more of) those checks can be circumvented like that, shouldn't we then rather fix those checks?

**Comment by Andersbakken** [comment]
I just actually want the file descriptor for debugging. E.g. I want it
returned even if it isn't a good socket anymore.

More importantly though, it seems like Curk_getconnectinfo fails in cases
even when the socket is still alive. Most notably when the request has been
multiplexed. The problem is that data->state.lastconnect is false if I
remember correctly.

Anders

**Comment by Andersbakken** [comment]
Happy New Year

We feel like it's relatively crucial for http2
multiplexing/weights/dependencies etc that it does indeed only use the one
socket for all requests to the same host so having it reliably report which
socket it used is of some importance to us. There may very well be a more
elegant solution to this. The key piece of information we want is whether
or not the request was pipelined/multiplexed. Is there another way we can
determine that?

regards

Anders

**Comment by bagder** [comment]
> it's relatively crucial for http2 multiplexing/weights/dependencies etc that it does indeed only use the one socket for all requests to the same host

I fully and strongly agree with that. But this change doesn't really improve that ability, it is just a way to extract debugging information and I'm concerned that it will break normal use.

Perhaps we can instead consider introducing a way to extract exactly the information you're asking for, instead of adding this quirk as a work-around? I mean, wouldn't it be even better for you if you could extract just the information "was this requested performed done on a re-used or a new connection" ? Possibly we could even make a counter for number of requests done over that connection, to allow better stats etc.

Thoughts?

**Comment by Andersbakken** [comment]
That would be excellent actually. Much better than my hack. Do you think
this is trivial?

Anders

**Comment by bagder** [comment]
Sure, at least it shouldn't be very hard. `conn->bits.reuse` is set TRUE on re-used connections so extracting that should at least be trivial. We could probably also add a counter next to that and return that on demand. Information about the transfer having been done multiplexed would need to be extracted differently.

**Comment by bagder** [comment]
If you want to take a first stab at something like that, I'd join in and assist. Let's close this one though since I think is the wrong thing.

**Comment by Andersbakken** [comment]
Hi Daniel

Will do. I'll send you a PR or an email when I have something.

regards

Anders

**Pull request closed without merging**
