### PR TITLE
The usage of MD5 and MD4 is not allowed by default in FIPS mode.

### PR DESCRIPTION
**Pull request by msmeissn**
Still valid usages must be flagged accordingly.

NTLM uses MD4 and MD5.
HTTP Digest auth uses MD5.

We could disallow both methods in FIPS mode, but it is currently probably
better to add allowance for those methods.

The patch also switches md4 and md5 to use the EVP interface of openssl instead of calling the lowlevel functions.

### CODE REVIEW

**Comment by captain-caveman2k** [comment]
Thanks Marcus,

I'll take a proper look at this when I get home tonight and all being well push it.

Kind Regards

Steve

**Comment by captain-caveman2k** [comment]
Hi Marcus,

I've download your pull request as a patch so I can compare and apply but first of all I was wondering:

* What version of OpenSSL the EVP functions are supported in? I couldn't find any reference in the API documentation or header files.
* What happens if EVP_MD_CTX_FLAG_NON_FIPS_ALLOW is not defined?
* I think we should take the opportunity to move the MD4 code from the NTLM code and into our own MD4 functions - just like we do for the MD5 code. What are your thoughts?
* I would also prefer to split the patch into two or more patches - one for the EVP change in NTLM, one for the EVP changes in MD5 and one for the FIPS changes (presuming that is the #ifndef(EVP_MD_CTX_FLAG_NON_FIPS_ALLOW ) chunk. What do you think?

Other minor observations worth noting:

* The commit comments don't follow our standards - please see http://curl.haxx.se/dev/contribute.html - although I can fix this up.
* The MD5 changes also don't follow our coding standards - tabs rather than two spaces - again I can fix this up.

Many thanks again

Kind Regards

Steve

**Comment by bagder** [comment]
Regarding any plans for larger changes like moving functions within MD4, please wait until I get a chance to merge my MD4 replacement I just posted to the list about!

**Comment by msmeissn** [comment]
EVP API - was already present in openssl 0.9.6g, so at least since 2002.

EVP_MD_CTX_FLAG_NON_FIPS_ALLOW - the #ifdef should handle it. The flag was introduced around openssl 0.9.8i to upstream as FIPS apis were added to openssl.

Moving to an internal md4 seems a good idea, people might build openssl without md4 support and upstream might even drop this in near future cleanups.

i can do some of the above cleanups

**Comment by bagder** [comment]
Thanks and I agree that a simple #ifdef should work fine there. If you just rebase your work on the current git you'll see that I replaced our MD4/MD5 code already.

**Comment by msmeissn** [comment]
As I have not done much work with github yet, please excuse some pull request breakage. :/

**Pull request closed without merging**
