### PR TITLE
build: Add wolfSSL configurations to Visual Studio project files

### PR DESCRIPTION
**Pull request by jay**
- Add wolfSSL configurations to Visual Studio 2010+ project files:

DLL Debug - DLL wolfSSL
DLL Release - DLL wolfSSL
LIB Debug - LIB wolfSSL
LIB Release - LIB wolfSSL

- Add wolfSSL Visual Studio build instructions.

### CODE REVIEW

**Comment by bagder** [comment]
@captain-caveman2k can you take a look/merge ?

**Comment by bagder** [comment]
Ah, and thanks a lot @jay for working on this (too) !

**Comment by jay** [comment]
I haven't gotten any feedback on this. I'm going to hold off for now and leave this open because besides that I think I'll add a build script for wolfssl similar to the build-openssl.bat so that it automates building wolfssl in a standard configuration compatible with libcurl for vc{10,11,12,etc}. Once I do that I'll have to change the directories in the project templates and then I'll poke someone for a review.

**Comment by jay** [comment]
Ok I've added the build-wolfssl script to automatically build wolfSSL and I've also updated the wolfSSL README and project templates. I've tested it in Visual Studio 2010 but not 2012 or 2013.

@captain-caveman2k do you think you could take a look at this before the feature window closes? It's a whole lot of XML (2k-3k lines) so I'd like to get a review if possible. If not can you or @bagder let me know who I should ping about this? Thanks!

**Comment by jay** [comment]
@bagder What do you recommend I do at this point. There's a lot of change here. I'd appreciate a second set of eyes and I'm not 100% on Steve's format (though a lot of the XML changes I made were generated by Visual Studio so they should be fine).

**Comment by captain-caveman2k** [comment]
Hi Guys,

Sorry for not being around over the last few months.

I spoke to Daniel a couple of weeks ago regarding my plans regarding curl so hopefully you should start to see a little more of me now.

I'm just downloading these changes now and will be back with some comments shortly ;-)

**Comment by captain-caveman2k** [comment]
Hey @jay,

I started taking a look at your changes last week and then spent the weekend concentrating on the VC14 project files (after Microsoft's release of Visual Studio 2015 last week). As you will have noticed I have slowing been pushing those changes over the last few days - which I am now done with ;-)

As such I am now taking a look at these changes. Perhaps @bagder would be so kind to assign this PR to be again ;-)

Anyway, I have a bunch of questions that, if it is okay with you, will ping over to you in a private email?

Cheers

Steve

**Comment by captain-caveman2k** [comment]
Note: I have a copy of your repo, have rebased against master and now have these 6 changes in a local branch against badger/curl.

**Comment by jay** [comment]
Steve, you're welcome to e-mail me. Generally speaking though for the benefit of the project and in the spirit of open source I prefer to keep everything that's not sensitive in some form of public record. Why don't you e-mail me for now (you've piqued my curiosity) and we can package a summary for this thread if it should be public. I reassigned this PR to you.

**Comment by captain-caveman2k** [comment]
Hi Guys,

I just wanted to post a summary of my queries following my emails with Jay over the last week as I have now pushed a compressed set of changes:

* Am I correct in thinking that the wolfSSL build script supports VC14 builds?
* Are the property sheet and header file from the "curl\projects" folder required and are they not part of the wolfSSL source package?
* Could the contents of the wolfSSL readme be added to the main README as some of the content seems relevant to our other build configurations?
* Is it possible to support wolfSSL in versions of Visual Studio prior to 2010 (VC10)?

As mentioned above I have now pushed two changes, which are compacted versions of Jay's changes which evolved since the original commit in March:

1) Addition of build-wolfssl.bat, header file and property sheet.

As build-wolfssl.bat is based on build-openssl.bat I have combined the later commit that fixes showing the syntax if the required arguments are missing as in my opinion the addition of build-wolfssl.bat should be based on the current build-openssl.bat ;-)

I updated Makefile.am so that build-wolfssl.bat is included in the release and daily snapshot archives. We will see overnight if I got that correct!!

2) Updates to the Visual Studio project files

As I pushed the commit to add build-wolfssl.bat first I couldn't see the point in having two separate commits, the first to add the configurations and the second to change the paths following the addition of build-wolfssl.bat. I also combined the third commit of adding the CYASSL pre-processor directive to the libcurl project files.

As I added the Visual Studio 2015 (VC14) project files the other week I have also added support for the wolfSSL configurations in those files as well (under the same commit that is credited to Jay rather than separately as me).

Obviously I renamed the curlsrc solution and project files to curl and updated output filenames to reflect that change - as such that cause me some pain and had to rework the commits to work with those changes.

I am still working on the README file - as some of Jay's wolfSSL readme is appropriate to our other configurations as well - this will be done over the next few days.

@bagder Do we have a preference of having these README files in plain text or in Markdown format? I'm happy to work with either.

**Pull request closed without merging**
