### PR TITLE
Initial changes to provide mbedtls 2.x support

### PR DESCRIPTION
**Pull request by fargly**
I have taken this as far as I can go.  Autoconf, configure, and make work correctly against both versions of mbedtls.  There is a conditional structure to handle the header file renames and the compatibility layer included in 2.x.  I made a single change in the polarssl.c code to accommodate an API change but ran aground just after the SSL initialization.  I don't know libcurl well enough to proceed but, hopefully, these changes can assist whomever has better libcurl kung fu than me.

Cheers

-Kurt

### CODE REVIEW

**Comment by bagder** [comment]
How does this PR relate to #385 ?

**Comment by fargly** [comment]
@hasufell <https://github.com/hasufell> did not keep any of the changes
relating to his efforts on #385, I was starting from scratch.
In order to get libcurl to recognize and use mbedtls 2.1.0, the minimum
appears necessary:

   1. Modify configure.ac to generate a configure script that detects
   mbedtls, both 1.x and 2.x
   2. Successfully run configure to generate makefiles that will function
   to build libcurl with mbedtls 2.x
   3. Due to the almost complete removal of support of 'polarssl' within
   mbedtls 2.x, provide #if conditionals to allow appropriate includes within
   libcurl code
   4. Lastly, polarssl.c needs to be modified to handle the API changes in
   mbedtls

mbedtls has altered what structures it expects in the function arguments.
The compatibility layer they (mbedtls) maintains is listed as deprecated.
It only remapped the function name changes and doesn't handle the inclusion
of new functions (i.e., ssl_init is now ssl_init and ssl_seed).  From line
321 in polarssl.c, most of the function calls have invalid argument sets
for mbedtls2.x. I'm not sure how you would want this handled, either a
single #if with separate code blocks for 1.x and 2.x, individual multiple
conditionals, or completely separate polarssl.c files for 1.x and 2.x.

The changes in my pull request get the build to the point that the API
cause errors.  I would need more information on how changes in polarssl.c
will affect the overall virtual tls layer (vtls) and not break anything
else in libcurl.

The changes are really the prep work but someone who has actual experience
as a contributor to libcurl may be better equipped to take this further.
The project I'm working on requires that I use the official release so I
cannot use any solution I come up with myself.

If you could advise where you would want my efforts to go, I certainly can
attempt to make those changes.

Regards

-Kurt

**Comment by bagder** [comment]
I could easily trim the configure to detect mbedtls instead, but I then fell into issues with mbedTLS. 

Their "compatibility layer" is sneakily tricking us into believing that `ssl_set_own_cert_rsa` still exists, while their Changelog says it was deprecated a while ago and it is nowhere to be found in the mbedtls code.

Lots of functions have new return codes or take different arguments.

I think we should consider mbedTLS to be different than PolarSSL and make a separate source file for it so that we can keep the PolarSSL support as-is (just in case we have users who care for that version we can keep it for a while before we ditch it) and then we adjust the new mbedtls.c file to use the current API only - instead.

Also, I of course plan on merging your work into curl once we know it is fairly good and at least doesn't damage anything existing so if we just cooperate this support will end up in a public release sooner or later.

**Comment by bagder** [comment]
Ah, and something else, consider adding '--enable-debug' to configure as then you'll get pickier compiler options and it will scan your code for obvious source style violations (it pointed out a few when I tried).

**Comment by fargly** [comment]
I did find a migration document in the mbedtls knowledge. I think your idea
of treating it as separate and distinct is the best course of action.
mbedtls probably should just state up front that 1.x and 2.x are quite
different and developers will have an easier time of it by just
reimplementing their code instead attempting to "straddle the fence" to
handle both versions.

I'll investigate further later this week.

Thanks

-Kurt

**Comment by sasq64** [comment]
I am too working on this. polarssl works fine for us but we need to use mbedtls because of the Apache license.
I already begun with a separate vtls/mbedtls.c file. I am not too familiar with autoconf so I will look at your changes for that.

**Comment by bagder** [comment]
@sasq64 you can probably get a decent first version by copying the polarssl check and just do a search/replace. If that isn't good enough, I can certainly offer my help to polish it to work. Possibly others can do. So if you just get the rest working, that won't be a problem.

**Comment by bagder** [comment]
Since you seem to be more than one person working on this, publishing a git branch for this work could be a good idea to get the collaboration going.

**Comment by bagder** [comment]
See #496

**Pull request closed without merging**
