### PR TITLE
updated AppVeyor build to handle OpenSSL/WinSSL builds

### PR DESCRIPTION
**Pull request by snikulov**
Updated AppVeyor build to:
- check build with OpenSSL turned ON/OFF (to avoid #617)
- updated version to current

### CODE REVIEW

**Comment by snikulov** [comment]
@bagder @jay Could you please merge?
I'll be notified if something will break Windows+CMake build.

**Comment by bagder** [comment]
Isn't there a better way to subscribe to these notifications, that would also allow anyone else with interest to do it? It feels wrong to add a hard-coded email address like this...

**Comment by snikulov** [comment]
Unfortunately, I'm unable to subscribe to builds from https://ci.appveyor.com/project/bagder/curl
It is your repository.
So if you'll be so kind to subscribe me using admin rights, I'll be very grateful :)

**Comment by snikulov** [comment]
@bagder removed notifications

**Comment by bagder** [comment]
thanks!

I have to admit that I've not figured out the best way for random people to sign up for the notifications. :-/

**Pull request closed without merging**
